### ISSUE TITLE
Cannot get static files casued by STATIC_URL setting error

### ISSUE THREAD

**Issue by 4tomic** [MobSF/Mobile-Security-Framework-MobSF#916]
## EXPLANATION OF THE ISSUE
cannot get static files

## STEPS TO REPRODUCE THE ISSUE

```
1. After installation complete on Windows Server 2012 R2
2.  executed `run.bat`
3. access `http://127.0.0.0:8000 using Firefox
4. get a nearly blank page(no CSS styles)
5. console shows cannot get static files 
```

## CONSOLE OUTPUT
![output](https://user-images.githubusercontent.com/9102271/55602647-34dca900-5799-11e9-9994-3f5aaf570120.png)

**Comment by ajinabraham** [comment]
Are you on the latest master. Should be fixed in the latest code.

**Comment by 4tomic** [comment]
Yes, latest master.

**Comment by ajinabraham** [comment]
Doesn't appear to be the latest form the logs you shared. The latest master runs on gunicorn server and not django development server. Do a `git pull`

**Comment by 4tomic** [comment]
Get it. I just cloned the code before your commit 4cbe3e33ded5c6b4b8a0ea9bbc295e6fd470c622.

But this time, after `git pull`, I did following things:
(I'm using Windows Server 2012 R2)

1. delete venv directory
2. execute `setup.bat`
3. execute `run.bat`

then the  console output
![console-output](https://user-images.githubusercontent.com/9102271/55603955-f72f4e80-579f-11e9-8f6d-e0d044b8ba47.png)

I searched `fcntl`, founding it does not support Windows. So is this a problem?

**Comment by 4tomic** [comment]
And, when using Django development server:
1. `venv\Scripts\activate`
2. `python manage.py runserver`
3. access `http://127.0.0.1:8000`

The static files still cannot be found.


Then change 
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/4cbe3e33ded5c6b4b8a0ea9bbc295e6fd470c622/MobSF/settings.py#L231
to `STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]` according to [django doc](https://docs.djangoproject.com/en/dev/howto/static-files/) and it worked.

**Comment by ajinabraham** [comment]
Thanks for pointing out. Will look into this.

**Comment by cctv0x01** [comment]
THX very much.Perfectly solved the same problem I encountered

**Comment by kec0a** [comment]
its work!
just change it:
#STATIC_ROOT = (
#    os.path.join(BASE_DIR, 'static/')
#)
STATICFILES_DIRS = [ os.path.join(BASE_DIR, "static") ]

THANK YOU!!!

**Comment by ajinabraham** [comment]
Related Duplicate: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/940

**Comment by ajinabraham** [comment]
Windows supported is restored in latest master
